### PR TITLE
Enhancement #32 implementation

### LINKED ISSUE #32: issue/0032: Improve Null-pointer exception handling
### Proposed solution

- Maximize usage of the `Objects.requireNonNull(Object, String)` facility when accepting user parameters, to provide more descriptive messages to probable the NullPointer Exceptions

## Additional details
- The code shall be developed in the `issue/0032` branch.

## Quality criteria
The following criteria will be observed during the Code Review:

#### Code coverage
- The produced code shall be secured by unit tests.
- Test coverage shall remain the same or increase.

#### Documentation
- All methods shall be documented with **Javadoc**, providing examples of usage.
- Javadoc pages shall be compilable with no errors or warnings
- README.md shall be updated if applicable

### PR DESCRIPTION
**Pull request by oswaldobapvicjr**

### CODE REVIEW

File: src/main/java/net/obvj/performetrics/monitors/MonitoredCallable.java [hunk 1]
```diff
@@ -46,49 +49,51 @@
...
+     * @param types    the counter types to be maintained with the operation
+     *
+     * @throws NullPointerException if the specified Runnable is null
      */
-    public MonitoredCallable(Callable<V> targetCallable, Type... types)
+    public MonitoredCallable(Callable<V> callable, Type... types)
     {
         super(types);
-        this.targetCallable = targetCallable;
+        this.callable = Objects.requireNonNull(callable, "The target Callable must not be null");
```
Comment (oswaldobapvicjr) [inline src/main/java/net/obvj/performetrics/monitors/MonitoredCallable.java]: Let the check be done inside call()
