### PR TITLE
Issue/0048: HTML errors while generating Javadoc

### LINKED ISSUE #48: HTML errors while generating Javadoc
### Observation

After migration to Github Actions, the Maven builds for JDKs 11 and 16 are failing at the Javadoc generation stage, with the following errors:

````
Error:  Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:jar (attach-javadocs) on project performetrics: MavenReportException: Error while generating Javadoc: 
Error:  Exit code: 1 - /home/runner/work/performetrics/performetrics/src/main/java/net/obvj/performetrics/util/DurationFormat.java:8: error: attribute not supported in HTML5: summary
Error:   * <table summary="Duration format examples">
Error:            ^
Error:  /home/runner/work/performetrics/performetrics/src/main/java/net/obvj/performetrics/util/print/PrintStyleBuilder.java:96: error: attribute not supported in HTML5: summary
Error:       * <table summary="Sequence of string positions by PrintFormat">
Error:                ^
Error:  /home/runner/work/performetrics/performetrics/src/main/java/net/obvj/performetrics/util/print/PrintStyleBuilder.java:149: error: attribute not supported in HTML5: summary
Error:       * <table summary="Sequence of string positions by PrintFormat">
Error:                ^
Error:  /home/runner/work/performetrics/performetrics/src/main/javadoc/overview.html:42: error: unexpected end tag: </p>
Error:      </p>
Error:      ^
Error:  
Error:  Command line was: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.11-9/x64/bin/javadoc @options @packages
Error:  
Error:  Refer to the generated Javadoc files in '/home/runner/work/performetrics/performetrics/target/apidocs' dir.
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.
````

## Additional details
- The code shall be developed in the `issue/0048` branch.

## Quality criteria
The following criteria will be observed during the Code Review:

#### Code coverage
- The produced code shall be secured by unit tests.
- Test coverage shall remain the same or increase.

#### Documentation
- All methods shall be documented with **Javadoc**, providing examples of usage.
- Javadoc pages shall be compilable with no errors or warnings
- README.md shall be updated if applicable

### PR DESCRIPTION
**Pull request by FernandoNSC5**
Updated Javadoc HTML to meet Java 11+ standards. #49

### CODE REVIEW

File: src/main/java/net/obvj/performetrics/util/DurationFormat.java [hunk 1]
```diff
@@ -5,7 +5,8 @@
  * <p>
  * Examples:
  * </p>
- * <table summary="Duration format examples">
+ * <table>
+ * <caption>Duration format examples</caption>
```
Comment (oswaldobapvicjr) [inline src/main/java/net/obvj/performetrics/util/DurationFormat.java]: After some brainstorming we decided to move away from HTML table and go with lists, to avoid the need for a caption or a summary.

**Comment by FernandoNSC5** [comment]
Opted by using `Lists` instead of `Tables` structures on Javadoc: The `<li>` tag is not closed as oracle documentation instructions. E.g.: [Javadoc HTML tags documentation](https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html#examples)

**Review by oswaldobapvicjr — APPROVED** [review]
Good job.
I took the opportunity to add more info and examples to the Javadoc.
