### PR TITLE
Pull request for fixing issue/0015 (#15)

### LINKED ISSUE #15: issue/0015 - Issue regarding arithmetic operations performed between Duration objects
## Trouble description

When performing a sum of Durations, an invalid result is observed:

Example 1:
```` java
Duration.of(500, MILLISECONDS).plus(Duration.of(500, MILLISECONDS).equals(Duration.of(1, SECOND));
// result = "false", but should be true
````

Actually, the resulting duration ended up with a nanoseconds part of 1000000000, instead of incrementing the seconds part.

After some analysis, it has been identified that moving to Java 8's Duration should be the smartest approach.

## Additional details
- The code shall be developed in the `issue/0015` branch.

## Quality criteria
The following criteria will be observed during the Code Review:

#### Code coverage
- The produced code shall be secured by unit tests.
- Test coverage shall remain the same or increase.

#### Documentation
- All methods shall be documented with **Javadoc**, providing examples of usage.
- Javadoc pages shall be compilable with no errors or warnings
- README.md shall be updated if applicable

### PR DESCRIPTION
**Pull request by oswaldobapvicjr**

### CODE REVIEW

File: src/main/java/net/obvj/performetrics/util/Duration.java [hunk 1]
```diff
@@ -424,30 +227,22 @@ public double toTimeUnit(TimeUnit timeUnit)
...
-        return targetHours.add(targetMinutes).add(targetSeconds).add(targetNanoseconds).doubleValue();
+        return targetSeconds.add(targetNanoseconds).doubleValue();
     }
 
     private BigDecimal convertNanosecondsPart(TimeUnit timeUnit, int scale)
     {
         return scale >= 0
-                ? BigDecimal.valueOf(TimeUnitConverter.convertAndRound(nanoseconds, TimeUnit.NANOSECONDS, timeUnit, scale))
-                : BigDecimal.valueOf(TimeUnitConverter.convertAndRound(nanoseconds, TimeUnit.NANOSECONDS, timeUnit));
+                ? BigDecimal.valueOf(TimeUnitConverter.convertAndRound(internalDuration.getNano(), TimeUnit.NANOSECONDS, timeUnit, scale))
```
Comment (oswaldobapvicjr) [inline src/main/java/net/obvj/performetrics/util/Duration.java]: Extract the content of `internalDuration.getNanos()` to a local variable to avoid duplicating the expression.

File: src/main/java/net/obvj/performetrics/util/DurationFormat.java [hunk 2]
```diff
@@ -0,0 +1,193 @@
...
+            {
+                builder.append(duration.getSeconds());
+                if (duration.getNanoseconds() > 0)
+                {
+                    String nanos = removeTrailingZeros(String.format(NANOSECONDS_FORMAT, duration.getNanoseconds()));
+                    builder.append(".").append(nanos);
+                }
+                builder.append('S');
+            }
+            return builder.toString();
```
Comment (oswaldobapvicjr) [inline src/main/java/net/obvj/performetrics/util/DurationFormat.java]: Check if this is really needed now that we have the internal duration available.

File: src/main/java/net/obvj/performetrics/util/DurationFormat.java [hunk 3]
```diff
@@ -0,0 +1,193 @@
...
+
+    /**
+     * Returns the {@code legend}, prepended with a white-space, if the
+     * {@code printLegendFlag} argument is {@code true}; or an empty string, otherwise.
+     *
+     * @param printLegendFlag the flag to be evaluated
+     * @param legend          the string to be used as legend
+     * @return the legend string
+     */
+    static String legend(boolean printLegendFlag, final String legend)
```
Comment (oswaldobapvicjr) [inline src/main/java/net/obvj/performetrics/util/DurationFormat.java]: Maybe this method can become private now?

File: src/test/java/net/obvj/performetrics/util/DurationFormatterTest.java [hunk 4]
```diff
@@ -0,0 +1,64 @@
...
+import static org.hamcrest.Matchers.is;
+import static net.obvj.performetrics.util.DurationFormat.*;
+
+import org.junit.Test;
+
+/**
+ * Test methods for the {@link DurationFormatter} class.
+ *
+ * @author oswaldo.bapvic.jr
+ */
```
Comment (oswaldobapvicjr) [inline src/test/java/net/obvj/performetrics/util/DurationFormatterTest.java:20]: Add the @since flag

**Review by oswaldobapvicjr — COMMENTED** [review]
Small issues concerning mainly modifiers and Javadoc found.
